// Test Jenkinsfile to verify that the program runs as intended. This is intended for Linux

pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                withPythonEnv('python') {
                    sh "python --version"
                }

                withPythonEnv(pythonInstallation: '/usr/bin/python3', pythonEnvInstallation: '/usr/bin/pypy') {
                    sh "python --version"
                }
            }
        }
    }
}